/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * SpringBoot-init - version 1.0.0
 *
 * SpringBoot-init
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.updateUser': ['PUT', '/user/update'],
  'general.updateUserStatus': ['PUT', '/user/update/status'],
  'general.updateProfile': ['PUT', '/user/update/profile'],
  'general.updatePassword': ['POST', '/user/update-password'],
  'general.resetUserPassword': ['POST', '/user/reset-password'],
  'general.userRegister': ['POST', '/user/register'],
  'general.userLogin': ['POST', '/user/login'],
  'general.addUser': ['POST', '/user/add'],
  'general.uploadFile': ['POST', '/file/upload'],
  'general.getUserPage': ['GET', '/user/page'],
  'general.getUser': ['GET', '/user/get'],
  'general.getUserVO': ['GET', '/user/get/vo'],
  'general.getLoginUser': ['GET', '/user/get/login'],
  'general.logout': ['DELETE', '/user/logout'],
  'general.deleteUser': ['DELETE', '/user/delete']
};
